# Generated by Django 4.2.3 on 2023-07-08 12:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_product_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(1970, 1, 1, 3, 0)),
        ),
    ]
